# Generated by Django 2.1.7 on 2019-04-08 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0002_auto_20190406_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='message',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select the user you want to play a game with',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
