# Generated by Django 2.1.7 on 2019-04-08 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0003_auto_20190408_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received',
                                    to=settings.AUTH_USER_MODEL),
        ),
    ]
