# Generated by Django 2.1.7 on 2019-04-08 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('player', '0004_auto_20190408_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='message',
            field=models.CharField(blank=True, help_text="It's always nice to add a friendly message!", max_length=300,
                                   verbose_name='Optional Message'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(help_text='Please select the user you want to play a game with',
                                    on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received',
                                    to=settings.AUTH_USER_MODEL, verbose_name='User to invite'),
        ),
    ]
