# Generated by Django 2.1.7 on 2019-03-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
