# Generated by Django 2.1.7 on 2019-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gameplay', '0003_auto_20190406_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='by_first_player',
            field=models.BooleanField(editable=False),
        ),
    ]
